### ISSUE TITLE
can't run 

### ISSUE THREAD

**Issue by songzengbin** [hs-web/hsweb3-demo#1]
Caused by: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.objects.NativeArray to java.util.Collection
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:312) ~[na:1.8.0_25]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:307) ~[na:1.8.0_25]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.L:1$initialize(<eval>:276) ~[na:na]
	at org.hswebframework.web.starter.init.InitializeCallBack$$NashornJavaAdapter.execute(Unknown Source) ~[na:na]
	at org.hswebframework.web.starter.init.simple.SimpleDependencyInstaller.doInitialize(SimpleDependencyInstaller.java:47) ~[hsweb-spring-boot-starter-3.0-20170719.090021-7.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.doInstall(SystemInitialize.java:95) ~[hsweb-spring-boot-starter-3.0-20170719.090021-7.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:165) ~[hsweb-spring-boot-starter-3.0-20170719.090021-7.jar:na]
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:95) ~[hsweb-spring-boot-starter-3.0-20170719.090021-7.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	...

**Comment by zhou-hao** [comment]
update your jdk
