### ISSUE TITLE
hsweb3-demo启动失败

### ISSUE THREAD

**Issue by vito16** [hs-web/hsweb3-demo#15]
clone最新代码使用Application#main方法启动报错如下：

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-04-26 17:26:49.807 ERROR 2308 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:772) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.hswebframework.web.demo.Application.main(Application.java:34) [classes/:na]
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: format version ${project.version} error  
	at org.hswebframework.web.starter.init.SystemInitialize.initReadyToInstallDependencies(SystemInitialize.java:140) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:176) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:154) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	... 6 common frames omitted
Caused by: java.lang.UnsupportedOperationException: format version ${project.version} error  
	at org.hswebframework.web.starter.Version.setVersion(SystemVersion.java:209) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	at org.hswebframework.web.starter.SystemVersion$Dependency.setVersion(SystemVersion.java:128) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	at org.hswebframework.web.starter.SystemVersion$Dependency.fromMap(SystemVersion.java:162) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	at org.hswebframework.web.starter.init.DependencyInstaller.setup(DependencyInstaller.java:35) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	at jdk.nashorn.internal.scripts.Script$Recompilation$1$11$\^eval\_.L:1(<eval>:530) ~[na:na]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.:program(<eval>:1) ~[na:na]
	at jdk.nashorn.internal.runtime.ScriptFunctionData._jr$$mh$invokeExact(ScriptFunctionData.java) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:na]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:421) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine.access$300(NashornScriptEngine.java:73) ~[nashorn.jar:na]
	at jdk.nashorn.api.scripting.NashornScriptEngine$3.eval(NashornScriptEngine.java:514) ~[nashorn.jar:na]
	at org.hswebframework.expands.script.engine.common.CommonScriptEngine.execute(CommonScriptEngine.java:110) ~[hsweb-expands-script-3.0.0.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.initReadyToInstallDependencies(SystemInitialize.java:135) ~[hsweb-spring-boot-starter-3.0-20180424.101557-32.jar:na]
	... 9 common frames omitted

```

跟踪代码到了`org.hswebframework.web.starter.Version#setVersion(java.lang.String)`中的代码：
```
public void setVersion(String version) {
        if (null != version) {
            boolean snapshot = version.toLowerCase().contains("snapshot");
            version = version.toLowerCase().replace(".snapshot", "").replace("-snapshot", "");
            String[] ver = version.split("[.]");
            Integer[] numberVer = ListUtils.stringArr2intArr(ver);
            if (numberVer.length >= 1 && !Arrays.stream(numberVer).anyMatch(Objects::isNull)) {
                this.setVersion(numberVer[0], numberVer.length <= 1 ? 0 : numberVer[1], numberVer.length <= 2 ? 0 : numberVer[2], snapshot);
            } else {
                throw new UnsupportedOperationException("format version " + version + " error  ");
            }
        }
    }
```
此时numberVer有两个null值，报错。

**Comment by zhou-hao** [comment]
使用mvn compile 先试试。 应该是maven 的filter没起作用。导致配置文件里的变量没被替换。

**Comment by vito16** [comment]
`mvn compile`过后运行成功。
