### ISSUE TITLE
spring-boot:run和Application启动都未成功 Cannot cast jdk.nashorn.internal.objects.NativeArray to java.util.Collection

### ISSUE THREAD

**Issue by xinjiangyuangit** [hs-web/hsweb3-demo#23]
请教下是我jdk（jdk1.8.0_31）版本和tomcat（Apache Tomcat/8.5.31）问题还是什么问题
堆栈信息如下：
2018-10-09 15:51:05.884  INFO 7340 --- [           main] o.h.w.s.i.s.SimpleDependencyInstaller    : initialize [org.hswebframework.web/hsweb-demo] version 3.0.0-SNAPSHOT https://github.com/hs-web/
2018-10-09 15:51:05.931  INFO 7340 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-10-09 15:51:05.968 ERROR 7340 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at org.hswebframework.web.demo.Application.main(Application.java:33) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_31]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_31]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_31]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_31]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:527) [spring-boot-maven-plugin-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Caused by: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.objects.NativeArray to java.util.Collection
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:312) ~[na:1.8.0_31]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:307) ~[na:1.8.0_31]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.L:1$initialize(<eval>:286) ~[na:na]
	at org.hswebframework.web.starter.init.InitializeCallBack$$NashornJavaAdapter.execute(Unknown Source) ~[na:na]
	at org.hswebframework.web.starter.init.simple.SimpleDependencyInstaller.doInitialize(SimpleDependencyInstaller.java:47) ~[hsweb-spring-boot-starter-3.0.0.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.doInstall(SystemInitialize.java:103) ~[hsweb-spring-boot-starter-3.0.0.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:177) ~[hsweb-spring-boot-starter-3.0.0.jar:na]
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:154) ~[hsweb-spring-boot-starter-3.0.0.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.13.RELEASE.jar:1.5.13.RELEASE]
	... 12 common frames omitted

**Comment by zhou-hao** [comment]
请更新到最新的jdk8.  https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by xinjiangyuangit** [comment]
好的，tks

**Comment by xinjiangyuangit** [comment]
Started Application in 126.674 seconds (JVM running for 138.314)
跑起来了
