### ISSUE TITLE
你好,作者!启动的时候发生了异常.

### ISSUE THREAD

**Issue by JcRaymee** [hs-web/hsweb3-demo#3]
具体信息: SpringApplication.class类第527行抛出的.

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:772) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.hswebframework.web.demo.Application.main(Application.java:35) [classes/:na]
Caused by: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.objects.NativeArray to java.util.Collection
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:312) ~[na:1.8.0_25]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:307) ~[na:1.8.0_25]
	at jdk.nashorn.internal.scripts.Script$\^eval\_.L:1$initialize(<eval>:398) ~[na:na]
	at org.hswebframework.web.starter.init.InitializeCallBack$$NashornJavaAdapter.execute(Unknown Source) ~[na:na]
	at org.hswebframework.web.starter.init.simple.SimpleDependencyInstaller.doInitialize(SimpleDependencyInstaller.java:47) ~[hsweb-spring-boot-starter-3.0-20171211.114142-26.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.doInstall(SystemInitialize.java:103) ~[hsweb-spring-boot-starter-3.0-20171211.114142-26.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:177) ~[hsweb-spring-boot-starter-3.0-20171211.114142-26.jar:na]
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:154) ~[hsweb-spring-boot-starter-3.0-20171211.114142-26.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	... 6 common frames omitted

**Comment by zhou-hao** [comment]
请升级到最新的jdk1.8 这应该是低版本的1.8的bug
