### ISSUE TITLE
启动时报错，请问怎么解决？

### ISSUE THREAD

**Issue by bananaMachete** [hs-web/hsweb3-demo#32]
2019-07-01 10:56:44.917 ERROR 10176 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.hswebframework.web.demo.Application.main(Application.java:31)
Caused by: java.lang.IllegalArgumentException: No enum constant java.sql.JDBCType.[B@315F5FFB
	at java.lang.Enum.valueOf(Enum.java:238)
	at java.sql.JDBCType.valueOf(JDBCType.java:34)
	at org.hswebframework.ezorm.rdb.meta.parser.AbstractTableMetaParser$RDBColumnMetaDataWrapper.done(AbstractTableMetaParser.java:148)
	at org.hswebframework.ezorm.rdb.meta.parser.AbstractTableMetaParser$RDBColumnMetaDataWrapper.done(AbstractTableMetaParser.java:97)
	at org.hswebframework.ezorm.rdb.executor.AbstractJdbcSqlExecutor.list(AbstractJdbcSqlExecutor.java:170)
	at org.hswebframework.web.datasource.DefaultJdbcExecutor.list(DefaultJdbcExecutor.java:60)
	at org.hswebframework.web.datasource.DefaultJdbcExecutor$$FastClassBySpringCGLIB$$e48f22af.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:736)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:671)
	at org.hswebframework.web.datasource.DefaultJdbcExecutor$$EnhancerBySpringCGLIB$$8dcc96f0.list(<generated>)
	at org.hswebframework.ezorm.rdb.meta.parser.AbstractTableMetaParser.parse(AbstractTableMetaParser.java:70)
	at org.hswebframework.ezorm.rdb.meta.builder.simple.SimpleTableBuilder.commit(SimpleTableBuilder.java:94)
	at org.hswebframework.web.starter.init.SystemInitialize.initInstallInfo(SystemInitialize.java:184)
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:197)
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:166)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	... 6 common frames omitted
报错信息是上面的内容.

**Comment by zhou-hao** [comment]
什么数据库。

**Comment by bananaMachete** [comment]
mysql

**Comment by bananaMachete** [comment]
mysql，数据表初始化已经有了。
![image](https://user-images.githubusercontent.com/32863117/60413005-f45cc200-9c05-11e9-8bd5-3c7c7800b75c.png)

**Comment by zhou-hao** [comment]
版本多少

**Comment by bananaMachete** [comment]
8.0

**Comment by zhou-hao** [comment]
换5.7试试吧。 8.0我没测试过

**Comment by bananaMachete** [comment]
好吧
