### ISSUE TITLE
编译通过无法运行

### ISSUE THREAD

**Issue by kigkrazy** [hs-web/hsweb3-demo#5]
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:772) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.hswebframework.web.demo.Application.main(Application.java:31) [classes/:na]
Caused by: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.objects.NativeArray to java.util.Collection
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361) ~[na:1.8.0_45]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356) ~[na:1.8.0_45]
	at jdk.nashorn.internal.scripts.Script$Recompilation$6$21189A$\^eval\_.L:1$initialize(<eval>:478) ~[na:na]
	at org.hswebframework.web.starter.init.InitializeCallBack$$NashornJavaAdapter.execute(Unknown Source) ~[na:na]
	at org.hswebframework.web.starter.init.simple.SimpleDependencyInstaller.doInitialize(SimpleDependencyInstaller.java:47) ~[hsweb-spring-boot-starter-3.0-20171221.071547-28.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.doInstall(SystemInitialize.java:103) ~[hsweb-spring-boot-starter-3.0-20171221.071547-28.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:177) ~[hsweb-spring-boot-starter-3.0-20171221.071547-28.jar:na]
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:154) ~[hsweb-spring-boot-starter-3.0-20171221.071547-28.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	... 6 common frames omitted

```

**Comment by zhou-hao** [comment]
请使用最新的 jdk8 运行
