### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by kigkrazy** [hs-web/hsweb3-demo#8]
```
2018-02-04 22:20:46.704 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : Releasing DataSource (default) JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@5a20f793]
2018-02-04 22:20:46.704 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : ==>  Preparing: SELECT count(0) as "total" FROM s_file_info s_file_info
2018-02-04 22:20:46.704 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : DataSource (default) JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@5a20f793] will not be managed by Spring
2018-02-04 22:20:46.704 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : <==      total: 1
2018-02-04 22:20:46.704 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : Releasing DataSource (default) JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@5a20f793]
2018-02-04 22:20:46.704 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : ==>  Preparing: COMMENT ON COLUMN s_file_info.u_id IS 'ID'
2018-02-04 22:20:46.704 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : DataSource (default) JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@5a20f793] will be managed by Spring
2018-02-04 22:20:46.705 DEBUG 5612 --- [           main] o.h.web.datasource.DefaultJdbcExecutor   : Releasing DataSource (default) JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@5a20f793]
2018-02-04 22:20:46.706  INFO 5612 --- [           main] o.h.w.s.i.s.SimpleDependencyInstaller    : initialize [org.hswebframework.web/hsweb-demo] version 3.0.0-SNAPSHOT https://github.com/hs-web/
2018-02-04 22:20:46.714  INFO 5612 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2018-02-04 22:20:46.725 ERROR 5612 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:804) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:772) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	at org.hswebframework.web.demo.Application.main(Application.java:31) [classes/:na]
Caused by: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.objects.NativeArray to java.util.Collection
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361) ~[na:1.8.0_45]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356) ~[na:1.8.0_45]
	at jdk.nashorn.internal.scripts.Script$Recompilation$6$21730A$\^eval\_.L:1$initialize(<eval>:500) ~[na:na]
	at org.hswebframework.web.starter.init.InitializeCallBack$$NashornJavaAdapter.execute(Unknown Source) ~[na:na]
	at org.hswebframework.web.starter.init.simple.SimpleDependencyInstaller.doInitialize(SimpleDependencyInstaller.java:47) ~[hsweb-spring-boot-starter-3.0-20180202.134224-31.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.doInstall(SystemInitialize.java:103) ~[hsweb-spring-boot-starter-3.0-20180202.134224-31.jar:na]
	at org.hswebframework.web.starter.init.SystemInitialize.install(SystemInitialize.java:177) ~[hsweb-spring-boot-starter-3.0-20180202.134224-31.jar:na]
	at org.hswebframework.web.starter.SystemInitializeAutoConfiguration.run(SystemInitializeAutoConfiguration.java:154) ~[hsweb-spring-boot-starter-3.0-20180202.134224-31.jar:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:801) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
	... 6 common frames omitted

2018-02-04 22:20:46.726  INFO 5612 --- [           main] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3a7442c7: startup date [Sun Feb 04 22:20:35 CST 2018]; root of context hierarchy
2018-02-04 22:20:46.727  INFO 5612 --- [           main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2018-02-04 22:20:46.728  INFO 5612 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2018-02-04 22:20:46.728  INFO 5612 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans
2018-02-04 22:20:46.729  INFO 5612 --- [           main] o.s.s.quartz.SchedulerFactoryBean        : Shutting down Quartz Scheduler
2018-02-04 22:20:46.729  INFO 5612 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler scheduler_$_NON_CLUSTERED shutting down.
2018-02-04 22:20:46.729  INFO 5612 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler scheduler_$_NON_CLUSTERED paused.
2018-02-04 22:20:46.951  INFO 5612 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler scheduler_$_NON_CLUSTERED shutdown complete.
2018-02-04 22:20:46.963  INFO 5612 --- [           main] com.alibaba.druid.pool.DruidDataSource   : {dataSource-1} closed

Process finished with exit code 1

```
环境:jdk1.8.0_45

**Comment by kigkrazy** [comment]
已经解决了，由于JDK版本太低导致的。换成jdk1.8.0_161即可正常运行。
